server:
  port: ${PORT:80}
  
spring:  jpa:    hibernate:      ddl-auto: create
    show-sql: true
    open-in-view: false
    
    # (MySQL version > 5.1 인 경우)  -> MySQL5InnoDBDialect else MySQLInnoDBDialect     database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  main:    allow-bean-definition-overriding: true
    
  datasource:    url: jdbc:mysql://remotemysql.com:3306/oIDj79884W
    username: oIDj79884W
    password: OmzIpgbOkP
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: embedded

  #authorization 인증 서버 접속 계정 정보
  security:    user:      name: admin
      password: admin
      roles:      - read
      
#아래가 client 접속 계정 정보 -> 예를 들어서 카톡, 페이스북, github 와 같은 곳에서 받은 client id 와 client secret 을 저장한다.      
security:
  oauth2:    client:      client-id: auth
      client-secret: authsec
      
  
#      grant-type: authorization-code